/**
 * Centralized UI strings for YojnaSathi frontend.
 * Supports English (en - default), Hindi (hi), and Marathi (mr).
 * Strictly avoids definitive legal qualification claims.
 */
export const STRINGS = {
  en: {
    // Header
    appTitle: "YojnaSathi",
    appTagline: "Find government schemes made simple",
    newSearch: "New Search",
    homeNav: "Home",
    languageSelect: "Language",
    mainNav: "Main navigation",
    navSchemeFinder: "Scheme Finder",
    navVoiceAssistant: "Voice Assistant",

    // Home Page & Category Grid
    heroBadge: "Civic Scheme Discovery",
    heroTitle: "Find government schemes made for you",
    heroSubtitle: "Answer a few simple questions and discover schemes that may be relevant to you.",
    categoryHeading: "What kind of help are you looking for?",
    categorySubtitle: "Select a category to start finding schemes tailored to your needs.",

    // Homepage Three Gateways
    homeHeroTitle: "Find government schemes easily",
    homeHeroSubtitle: "Choose how you'd like to get help. It only takes a minute.",
    gatewayWebsiteTitle: "I can use a website",
    gatewayWebsiteDesc: "Browse and find schemes by yourself",
    gatewayWebsiteCta: "Find Schemes Online",
    gatewayVoiceTitle: "I want to speak",
    gatewayVoiceDesc: "Talk to the YojnaSathi assistant",
    gatewayVoiceCta: "Speak with YojnaSathi",
    gatewayPhoneTitle: "Phone / CALL-E",
    gatewayPhoneDesc: "Don't use websites? YojnaSathi will provide an AI-powered phone assistant.",
    gatewayPhoneCta: "Call YojnaSathi",
    gatewayPhoneNote: "Coming Soon",
    gatewayPhoneJudgeNote:
      "CALL-E inbound calling requires a paid phone number and will be added in the next phase. The CALL-E integration and shared YojnaSathi scheme-matching architecture are already implemented in this MVP.",
    gatewaySecondaryHeading: "Other ways to get help",
    gatewayVoicePrimaryLabel: "Talk to me",
    gatewayVoicePrimaryHint: "Tap anywhere to speak",
    gatewayVoicePrimaryAria: "Talk to YojnaSathi in your own language",
    quickTopicsHeading: "Quick topics",
    quickTopicsSubtitle: "Popular topics to get you started",

    // Categories
    catFarmersTitle: "Farmers",
    catFarmersDesc: "Farming, crop insurance, and financial support.",
    catWomenTitle: "Women",
    catWomenDesc: "Support, financial assistance, and welfare schemes.",
    catEducationTitle: "Education",
    catEducationDesc: "Scholarships, student support, and education schemes.",
    catHealthcareTitle: "Healthcare",
    catHealthcareDesc: "Health insurance and medical support.",
    catHousingTitle: "Housing",
    catHousingDesc: "Housing assistance and related schemes.",
    catEmploymentTitle: "Employment",
    catEmploymentDesc: "Jobs, skills, and employment support.",
    catBusinessTitle: "Small Business",
    catBusinessDesc: "Loans and support for businesses and street vendors.",

    // Questionnaire
    questionnaireTitlePrefix: "Finding schemes for",
    questionnaireSubtitle: "Let's find schemes that may be useful for you. This will only take a minute.",
    stepIndicator: "Step {current} of {total}",
    backButton: "← Back",
    continueButton: "Continue →",
    submitButton: "Find Relevant Schemes 🎯",
    findingSchemesLoading: "Finding schemes that may be relevant to you...",
    selectOptionPrompt: "Please select an option to continue.",

    // Questionnaire Common Questions
    ageQuestion: "How old are you?",
    agePlaceholder: "Enter your age in years (e.g. 35)",
    ageError: "Please enter a valid age between 10 and 120 years.",
    stateQuestion: "Where do you live?",
    statePlaceholder: "-- Select your State / UT --",
    stateError: "Please select your state from the list.",
    districtQuestion: "Which district do you live in?",
    districtPlaceholder: "-- Select District (or Skip) --",
    districtPilotNote: "Pilot Phase: Physical application offices are currently cataloged for Nashik and Pune districts. You may choose 'Other' or skip for statewide schemes.",
    talukaQuestion: "Which taluka (block) do you live in?",
    talukaPlaceholder: "-- Select Taluka (or Skip) --",
    otherDistrictOption: "Other District / Skip",
    otherTalukaOption: "Other Taluka / Skip",
    loadingDistricts: "Loading official districts...",
    loadingTalukas: "Loading official talukas...",
    errorLoadingDistricts: "Unable to load districts right now.",
    errorLoadingTalukas: "Unable to load talukas right now.",
    retryLocationButton: "Retry",
    incomeQuestion: "What is your approximate yearly family income?",
    incomeBelow25: "Below ₹2.5 Lakh",
    income25to6: "₹2.5 Lakh – ₹6 Lakh",
    incomeAbove6: "Above ₹6 Lakh",
    incomeDontKnow: "I don't know / Prefer not to say",

    // Social Category Questions
    socialCategoryQuestion: "Which social category do you belong to?",
    socialCatGeneral: "General / Open Category",
    socialCatSC: "Scheduled Caste (SC)",
    socialCatST: "Scheduled Tribe (ST)",
    socialCatOBC: "Other Backward Class (OBC)",
    socialCatEBC: "Economically Backward Class (EBC)",
    socialCatDNT: "De-notified, Nomadic or Semi-Nomadic Tribe (DNT / NT)",
    socialCatDontKnow: "I don't know / Prefer not to say",

    // Rural / Urban Area Questions
    areaQuestion: "Do you reside in a rural village or an urban city area?",
    areaRural: "Rural village area",
    areaUrban: "Urban city / town area",
    areaDontKnow: "I don't know / Not sure",

    // Farmers Questions
    farmerLandQuestion: "Do you or your family own cultivable agricultural land?",
    farmerLandYes: "Yes, we own agricultural land",
    farmerLandNo: "No, tenant/sharecropper or landless",
    farmerLandDontKnow: "I don't know / Not sure",
    farmerNeedQuestion: "What kind of help do you need?",
    farmerNeedCropInsurance: "Crop insurance (protection against crop damage)",
    farmerNeedDirectSupport: "Direct financial support (income support for farmers)",
    farmerNeedEquipment: "Farming equipment & agricultural inputs",
    farmerNeedLoan: "Agricultural credit or loan",

    // Women Questions
    womenStatusQuestion: "What is your current situation?",
    womenStatusMarried: "Married woman",
    womenStatusUnmarried: "Unmarried woman",
    womenStatusPregnant: "Pregnant or lactating mother",
    womenStatusWidow: "Widow, deserted, or single woman",
    womenStatusGeneral: "Prefer not to specify",
    womenNeedQuestion: "What kind of support are you looking for?",
    womenNeedFinance: "Monthly financial assistance for women",
    womenNeedGas: "Free LPG / cooking gas connection",
    womenNeedMaternity: "Maternity & pregnancy financial assistance",
    womenNeedTraining: "Skill training & self-employment support",

    // Education Questions
    eduStatusQuestion: "Are you currently a student or pursuing education?",
    eduStatusYes: "Yes, currently studying in school/college",
    eduStatusNo: "No, seeking educational opportunities/skill training",
    eduNeedQuestion: "What type of educational support do you need?",
    eduNeedScholarship: "School or pre/post-matric scholarship",
    eduNeedHigherEdu: "Higher education financial support & coaching",
    eduNeedSkill: "Skill development & vocational certification",

    // Healthcare Questions
    healthNeedQuestion: "What kind of healthcare assistance do you need?",
    healthNeedHospital: "Hospital treatment & surgery cover",
    healthNeedInsurance: "Free health insurance card (up to ₹5 Lakh)",
    healthNeedSenior: "Senior citizen health coverage (Age 70+)",
    healthNeedCritical: "Critical illness or hospitalization support",

    // Housing Questions
    housingPuccaQuestion: "Do you or your family currently own a pucca (permanent) house?",
    housingPuccaNo: "No, living in kutcha house, temporary shelter, or rented",
    housingPuccaYes: "Yes, we own a permanent pucca house",
    housingPuccaDontKnow: "I don't know / Not sure",
    housingAreaQuestion: "Where are you planning to construct or buy a house?",
    housingAreaRural: "Rural village area (PMAY-Gramin)",
    housingAreaUrban: "Urban / city / municipal area (PMAY-Urban)",

    // Employment Questions
    empStatusQuestion: "What is your current employment status?",
    empStatusUnemployed: "Job seeker / Unemployed",
    empStatusWage: "Daily wage worker / Rural laborer",
    empStatusYouth: "Youth seeking skill training & certification",
    empStatusUnorganized: "Unorganized sector worker",
    empNeedQuestion: "What kind of employment support do you need?",
    empNeedWage: "100 days guaranteed rural wage employment (MGNREGA)",
    empNeedSkill: "Free skill development & industry training (PMKVY)",
    empNeedPension: "Old-age pension & retirement security (APY)",
    empNeedAccident: "Low-cost accidental insurance cover (PMSBY)",

    // Small Business Questions
    bizStatusQuestion: "What type of business activity do you do?",
    bizStatusVendor: "Street vendor / Cart vendor / Hawker",
    bizStatusSmallBiz: "Small business / Retail shop owner",
    bizStatusSelf: "Micro-entrepreneur / Self-employed",
    bizStatusAspiring: "Planning to start a new micro-enterprise",
    bizNeedQuestion: "What kind of financial assistance do you need?",
    bizNeedWorkingCap: "Collateral-free working capital loan (PM SVANidhi)",
    bizNeedMudra: "Business loan for micro-enterprise (MUDRA)",
    bizNeedBank: "Zero-balance bank account with overdraft & insurance (PMJDY)",

    // Results Page
    resultsTitle: "Schemes that may be relevant to you",
    resultsCountPrefix: "We found",
    resultsCountSuffix: "schemes based on the information you provided.",
    noticeLabel: "Notice:",
    disclaimerText: "These schemes are potentially relevant based on the information provided. Final eligibility is determined by the relevant government authority.",
    noResultsTitle: "We couldn't find schemes that closely match the information provided",
    noResultsText: "Based on the information provided, we could not find directly matching schemes in this category. Try adjusting your answers or starting a new search.",
    changeAnswers: "Change Answers",
    startNewSearch: "Start New Search",

    // Web Scheme Discovery (independent Tavily pipeline, user-initiated)
    webSearchTitle: "More schemes from the web",
    webSearchDesc: "Found a scheme missing above? Search official government websites for additional schemes beyond our verified list.",
    webSearchCta: "Search the web for more schemes",
    webSearchLoading: "Searching official government websites... This may take up to 30 seconds.",
    webSearchBadge: "Found on web",
    webSearchVerifyLink: "Verify on official portal",
    webSearchDisclaimer: "These schemes were found on the web and may be relevant. Always verify benefits and eligibility on the linked official portal. Final eligibility is determined by the relevant government authority.",
    webSearchRejectedNote: "Additional unverified results withheld",
    webSearchUnavailable: "Web search is temporarily unavailable or found no additional verified schemes. Your verified results above are unaffected.",
    webSearchNetworkError: "Could not reach the server. Please check your connection and try again.",
    webSearchGenericError: "Web search failed. Please try again later.",

    // Scheme Card
    liveGovSource: "Live • Government Source",
    liveGovSourceDesc: "Discovered and verified from official government portals",
    matchRelevance: "Match relevance:",
    whyRelevant: "Why this may be relevant",
    infoNeeded: "Information you may need",
    viewDetails: "View Scheme Details",
    hideDetails: "Hide Details",

    // Scheme Card Guidance (What do I do next?)
    nextStepsTitle: "What do I do next?",
    stepCheckEligibility: "Confirm you meet the eligibility conditions for this scheme",
    stepPrepareDocuments: "Gather the information and documents listed above",
    stepApplyOnline: "Fill and submit the online application at the official portal",
    stepTrackStatus: "Track your application status using the portal's reference number",
    portalLabel: "Official portal:",
    applyOnlineButton: "Apply Online ↗",
    applyOfflineLabel: "Apply Offline",
    schemeDataInfoMissing: "Application details are not available in the current scheme data.",
    whereToApplyTitle: "Where can I apply? (Physical Offices)",
    noLocationsFound: "No physical office registered for this scheme in your selected jurisdiction. You can apply online via the official portal.",
    officeOfficialSource: "Official Portal",

    // Dynamic Reason Codes
    reason_ALL_INDIA_AVAILABLE: "Applicable across India, including {state}",
    reason_STATE_SPECIFIC_MATCH: "Specifically available for residents of {state}",
    reason_TARGET_GROUP_FARMER: "Relevant for farmers and rural citizens",
    reason_TARGET_GROUP_STUDENT: "Relevant for students and youth",
    reason_TARGET_GROUP_WOMEN: "Provides targeted support for women",
    reason_TARGET_GROUP_BUSINESS: "Relevant for small businesses, vendors, and entrepreneurs",
    reason_TARGET_GROUP_WORKER: "Relevant for unorganized and unskilled workers",
    reason_NEED_MATCH: "Matches your selected interest in this scheme category",
    reason_AGE_CRITERIA_MATCH: "Your age ({age} years) matches the scheme criteria",
    reason_INCOME_CRITERIA_MATCH: "Your family income is within the scheme's threshold",
    reason_LAND_OWNERSHIP_MATCH: "Matches your agricultural landholding status",
    reason_SOCIAL_CATEGORY_MATCH: "Matches your social category ({category})",
    reason_AREA_MATCH: "Specifically designed for {area} areas",
    reason_HOUSING_NEED_MATCH: "Addresses households without a permanent pucca house",

    // Scheme Detail Modal
    modalTitle: "Scheme Details",
    departmentLabel: "Department / Ministry:",
    aboutLabel: "About this scheme",
    benefitsLabel: "Key Benefits",
    documentsLabel: "Information you may need",
    applyButton: "Apply / Learn more ↗",
    sourceButton: "Official source portal ↗",
    closeModal: "Close",
    loadingDetails: "Loading verified scheme information...",

    // Errors
    errorTitle: "We couldn't find your schemes right now.",
    errorGeneric: "An unexpected issue occurred while finding relevant schemes. Please try again.",
    errorNetwork: "Unable to connect to the YojnaSathi server. Please check your internet connection or verify the backend is running.",
    tryAgain: "Try Again",
    startOver: "Start Over",

    // Voice Assistant
    voicePageTitle: "Voice Assistant",
    voicePageSubtitle: "Speak in English, Hindi, or Marathi. The assistant will guide you to schemes that may be relevant.",
    voiceRobotGreeting: "Need help finding a scheme?",
    voiceWelcomeGreeting: "Hello! I'm YojnaSathi. Talk to me to find government schemes.",
    voicePanelTitle: "YojnaSathi Voice Assistant",
    voiceSelectLanguage: "Please select your language",
    voiceLangChoiceHint: "The assistant will speak in the language you choose.",
    voiceLangLockedHint: "Language is fixed for this conversation",
    voiceClosePanel: "Close voice assistant",
    voiceMicIdleHint: "Tap the microphone to speak",
    voiceMicHoldHint: "Hold to speak",
    voiceMicReleaseHint: "Release to send",
    voiceMicListening: "Listening…",
    voiceMicProcessing: "Finding schemes…",
    voiceMicSpeaking: "Speaking…",
    voiceMicIdle: "Tap to speak",
    voiceTapToSpeak: "Tap to speak",
    voiceNewConversation: "New Conversation",
    voiceStopSpeaking: "Stop playback",
    voiceYouSaid: "You said",
    voiceAssistantSaid: "Assistant",
    voiceAssistantLabel: "YojnaSathi Assistant",
    voiceUserLabel: "You",
    voicePlayResponse: "Play response",
    voiceReplayResponse: "Replay response",
    voiceTranscriptLabel: "Voice agent conversation",
    voiceSchemesIntro: "Here are some schemes that may be relevant to you:",
    voiceStarterHeading: "Try asking:",
    voiceStarterFarmer: "Farmer support in Maharashtra",
    voiceStarterScholarship: "Scholarship for students",
    voiceStarterHousing: "Housing assistance",
    voicePlaceholder: "Or type your question here…",
    voiceSendLabel: "Send message",
    voiceErrorTitle: "Sorry, something went wrong.",
    voiceErrorNetwork: "Unable to reach the server. Please check your connection and try again.",
    voiceErrorGeneric: "We couldn't complete your request. Please try again.",
    voiceRetry: "Try Again",
    voiceErrorMicPermission: "Microphone access was blocked. Please allow microphone access in your browser and try again.",
    voiceErrorMicUnavailable: "The microphone is unavailable right now. Please check your audio devices and try again.",
    voiceErrorNoMicrophone: "No microphone was found on this device.",
    voiceErrorUnsupported: "Your browser doesn't support voice input. Please use a recent version of Chrome, Edge, or Firefox.",
    voiceErrorEmptyRecording: "No speech was detected. Please hold the microphone and speak again.",
    voiceErrorTts: "Voice playback was unavailable, but the assistant response is shown below.",
    voicePlayBackFailed: "Audio playback was blocked by the browser. Tap “Play response” to listen.",
  },

  hi: {
    // Header
    appTitle: "योजनासाथी",
    appTagline: "सरकारी योजनाएं खोजना हुआ आसान",
    newSearch: "नई खोज",
    homeNav: "मुख्य पृष्ठ",
    languageSelect: "भाषा",
    mainNav: "मुख्य नेविगेशन",
    navSchemeFinder: "योजना खोज",
    navVoiceAssistant: "वॉयस असिस्टेंट",

    // Home Page & Category Grid
    heroBadge: "नागरिक योजना खोज मंच",
    heroTitle: "अपने लिए उपयुक्त सरकारी योजनाएं खोजें",
    heroSubtitle: "कुछ आसान सवालों के जवाब दें और अपने लिए प्रासंगिक सरकारी योजनाएं जानें।",
    categoryHeading: "आप किस प्रकार की सहायता खोज रहे हैं?",
    categorySubtitle: "अपनी आवश्यकता के अनुसार उपयुक्त श्रेणी चुनें।",

    // Homepage Three Gateways
    homeHeroTitle: "सरकारी योजनाएं आसानी से खोजें",
    homeHeroSubtitle: "चुनें कि आप किस तरह से मदद चाहते हैं। इसमें बस एक मिनट लगेगा।",
    gatewayWebsiteTitle: "मैं वेबसाइट का उपयोग कर सकता/कर सकती हूँ",
    gatewayWebsiteDesc: "योजनाएं स्वयं ब्राउज़ करें और खोजें",
    gatewayWebsiteCta: "ऑनलाइन योजनाएं खोजें",
    gatewayVoiceTitle: "मैं बोलकर खोजना चाहता/चाहती हूँ",
    gatewayVoiceDesc: "योजनासाथी असिस्टेंट से बात करें",
    gatewayVoiceCta: "योजनासाथी से बात करें",
    gatewayPhoneTitle: "फ़ोन / कॉल-ई",
    gatewayPhoneDesc: "वेबसाइट का उपयोग नहीं करते? योजनासाथी एक AI-संचालित फ़ोन सहायक प्रदान करेगा।",
    gatewayPhoneCta: "योजनासाथी को कॉल करें",
    gatewayPhoneNote: "जल्द ही आ रहा है",
    gatewayPhoneJudgeNote:
      "CALL-E इनबाउंड कॉलिंग के लिए एक पेड फ़ोन नंबर आवश्यक है और इसे अगले चरण में जोड़ा जाएगा। CALL-E इंटीग्रेशन और साझा योजनासाथी स्कीम-मैचिंग आर्किटेक्चर इस MVP में पहले से लागू हैं।",
    gatewaySecondaryHeading: "मदद पाने के अन्य तरीके",
    gatewayVoicePrimaryLabel: "मुझसे बात करें",
    gatewayVoicePrimaryHint: "बोलने के लिए कहीं भी दबाएं",
    gatewayVoicePrimaryAria: "अपनी ही भाषा में योजनासाथी से बात करें",
    quickTopicsHeading: "त्वरित विषय",
    quickTopicsSubtitle: "आसानी से शुरुआत करने के लिए लोकप्रिय विषय",

    // Categories
    catFarmersTitle: "किसान",
    catFarmersDesc: "खेती, फसल बीमा और वित्तीय सहायता योजनाएं।",
    catWomenTitle: "महिलाएं",
    catWomenDesc: "सहायता, वित्तीय लाभ और महिला कल्याण योजनाएं।",
    catEducationTitle: "शिक्षा एवं छात्र",
    catEducationDesc: "छात्रवृत्ति, विद्यार्थी सहायता और उच्च शिक्षा योजनाएं।",
    catHealthcareTitle: "स्वास्थ्य सेवा",
    catHealthcareDesc: "स्वास्थ्य बीमा और निःशुल्क चिकित्सा उपचार सहायता।",
    catHousingTitle: "आवास योजना",
    catHousingDesc: "पक्का मकान निर्माण और आवास सहायता योजनाएं।",
    catEmploymentTitle: "रोजगार व कौशल",
    catEmploymentDesc: "रोजगार गारंटी, कौशल विकास और सामाजिक सुरक्षा।",
    catBusinessTitle: "लघु व्यवसाय",
    catBusinessDesc: "रेहड़ी-पटरी विक्रेता, मुद्रा लोन और व्यापार सहायता।",

    // Questionnaire
    questionnaireTitlePrefix: "के लिए योजनाएं खोज रहे हैं",
    questionnaireSubtitle: "आइए आपके लिए उपयुक्त योजनाएं खोजते हैं। इसमें केवल एक मिनट लगेगा।",
    stepIndicator: "चरण {current} / {total}",
    backButton: "← पीछे जाएं",
    continueButton: "आगे बढ़ें →",
    submitButton: "प्रासंगिक योजनाएं देखें 🎯",
    findingSchemesLoading: "आपके लिए प्रासंगिक योजनाएं खोजी जा रही हैं...",
    selectOptionPrompt: "कृपया आगे बढ़ने के लिए एक विकल्प चुनें।",

    // Questionnaire Common Questions
    ageQuestion: "आपकी उम्र कितनी है?",
    agePlaceholder: "अपनी उम्र दर्ज करें (उदा. 35)",
    ageError: "कृपया 10 से 120 वर्ष के बीच मान्य आयु दर्ज करें।",
    stateQuestion: "आप कहाँ रहते हैं?",
    statePlaceholder: "-- अपना राज्य / केंद्र शासित प्रदेश चुनें --",
    stateError: "कृपया सूची से अपना राज्य चुनें।",
    districtQuestion: "आप किस जिले में रहते हैं?",
    districtPlaceholder: "-- जिला चुनें (या छोड़ें) --",
    districtPilotNote: "पायलट चरण: भौतिक आवेदन कार्यालय वर्तमान में नाशिक और पुणे जिलों के लिए उपलब्ध हैं। आप 'अन्य' चुन सकते हैं या छोड़ सकते हैं।",
    talukaQuestion: "आप किस तालुका (प्रखंड) में रहते हैं?",
    talukaPlaceholder: "-- तालुका चुनें (या छोड़ें) --",
    otherDistrictOption: "अन्य जिला / छोड़ें",
    otherTalukaOption: "अन्य तालुका / छोड़ें",
    loadingDistricts: "आधिकारिक जिले लोड हो रहे हैं...",
    loadingTalukas: "आधिकारिक तालुका लोड हो रहे हैं...",
    errorLoadingDistricts: "वर्तमान में जिले लोड करने में असमर्थ।",
    errorLoadingTalukas: "वर्तमान में तालुका लोड करने में असमर्थ।",
    retryLocationButton: "पुनः प्रयास करें",
    incomeQuestion: "आपके परिवार की अनुमानित वार्षिक आय कितनी है?",
    incomeBelow25: "₹2.5 लाख से कम",
    income25to6: "₹2.5 लाख से ₹6 लाख",
    incomeAbove6: "₹6 लाख से अधिक",
    incomeDontKnow: "पता नहीं / बताना नहीं चाहते",

    // Social Category Questions
    socialCategoryQuestion: "आप किस सामाजिक वर्ग (श्रेणी) से संबंधित हैं?",
    socialCatGeneral: "सामान्य वर्ग (General)",
    socialCatSC: "अनुसूचित जाति (SC)",
    socialCatST: "अनुसूचित जनजाति (ST)",
    socialCatOBC: "अन्य पिछड़ा वर्ग (OBC)",
    socialCatEBC: "आर्थिक रूप से पिछड़ा वर्ग (EBC)",
    socialCatDNT: "विमुक्त, घुमंतू या अर्ध-घुमंतू जनजाति (DNT / NT)",
    socialCatDontKnow: "पता नहीं / बताना नहीं चाहते",

    // Rural / Urban Area Questions
    areaQuestion: "आप ग्रामीण गाँव में रहते हैं या शहरी क्षेत्र में?",
    areaRural: "ग्रामीण क्षेत्र (गाँव)",
    areaUrban: "शहरी क्षेत्र (शहर / कस्बा)",
    areaDontKnow: "पता नहीं / निश्चित नहीं",

    // Farmers Questions
    farmerLandQuestion: "क्या आपके या आपके परिवार के नाम कृषि योग्य भूमि है?",
    farmerLandYes: "हाँ, हमारे पास कृषि भूमि है",
    farmerLandNo: "नहीं, बटाईदार / पट्टेदार या भूमिहीन हैं",
    farmerLandDontKnow: "पता नहीं / निश्चित नहीं",
    farmerNeedQuestion: "आपको किस प्रकार की सहायता चाहिए?",
    farmerNeedCropInsurance: "फसल बीमा (फसल नुकसान से सुरक्षा)",
    farmerNeedDirectSupport: "प्रत्यक्ष वित्तीय सहायता (किसान सम्मान निधि)",
    farmerNeedEquipment: "कृषि उपकरण और खाद-बीज सहायता",
    farmerNeedLoan: "कृषि ऋण या किसान क्रेडिट कार्ड",

    // Women Questions
    womenStatusQuestion: "आपकी वर्तमान स्थिति क्या है?",
    womenStatusMarried: "विवाहित महिला",
    womenStatusUnmarried: "अविवाहित युवती / महिला",
    womenStatusPregnant: "गर्भवती या स्तनपान कराने वाली माता",
    womenStatusWidow: "विधवा, परित्यक्ता या एकल महिला",
    womenStatusGeneral: "बताना नहीं चाहते",
    womenNeedQuestion: "आप किस प्रकार की सहायता खोज रही हैं?",
    womenNeedFinance: "महिलाओं के लिए मासिक आर्थिक सहायता (लाड़की बहिन)",
    womenNeedGas: "निःशुल्क एलपीजी गैस सिलेंडर कनेक्शन (उज्ज्वला)",
    womenNeedMaternity: "मातृत्व एवं गर्भावस्था आर्थिक सहायता",
    womenNeedTraining: "कौशल प्रशिक्षण एवं स्वरोजगार सहायता",

    // Education Questions
    eduStatusQuestion: "क्या आप वर्तमान में छात्र हैं या पढ़ाई कर रहे हैं?",
    eduStatusYes: "हाँ, स्कूल या कॉलेज में पढ़ाई कर रहे हैं",
    eduStatusNo: "नहीं, शिक्षा या कौशल प्रशिक्षण के अवसर खोज रहे हैं",
    eduNeedQuestion: "आपको किस प्रकार की शैक्षणिक सहायता चाहिए?",
    eduNeedScholarship: "स्कूल या प्री/पोस्ट-मैट्रिक छात्रवृत्ति",
    eduNeedHigherEdu: "उच्च शिक्षा सहायता एवं प्रतियोगी परीक्षा कोचिंग",
    eduNeedSkill: "कौशल विकास एवं व्यावसायिक प्रमाणन",

    // Healthcare Questions
    healthNeedQuestion: "आपको किस प्रकार की स्वास्थ्य सहायता चाहिए?",
    healthNeedHospital: "अस्पताल में भर्ती, उपचार एवं ऑपरेशन सहायता",
    healthNeedInsurance: "निःशुल्क स्वास्थ्य बीमा कार्ड (₹5 लाख तक)",
    healthNeedSenior: "वरिष्ठ नागरिक स्वास्थ्य सुरक्षा (70 वर्ष और अधिक)",
    healthNeedCritical: "गंभीर बीमारी या चिकित्सा उपचार सहायता",

    // Housing Questions
    housingPuccaQuestion: "क्या आपके या आपके परिवार के पास पक्का मकान है?",
    housingPuccaNo: "नहीं, कच्चे मकान, झोपड़ी या किराए पर रहते हैं",
    housingPuccaYes: "हाँ, हमारे पास पक्का मकान है",
    housingPuccaDontKnow: "पता नहीं / निश्चित नहीं",
    housingAreaQuestion: "आप मकान कहाँ बनाने या खरीदने की योजना बना रहे हैं?",
    housingAreaRural: "ग्रामीण क्षेत्र / गाँव में (पीएम आवास ग्रामीण)",
    housingAreaUrban: "शहरी क्षेत्र / नगर पालिका क्षेत्र में (पीएम आवास शहरी)",

    // Employment Questions
    empStatusQuestion: "आपकी वर्तमान रोजगार स्थिति क्या है?",
    empStatusUnemployed: "बेरोजगार / काम की तलाश में",
    empStatusWage: "दैनिक वेतनभोगी मजदूर / ग्रामीण श्रमिक",
    empStatusYouth: "युवा जो कौशल प्रशिक्षण पाना चाहते हैं",
    empStatusUnorganized: "असंगठित क्षेत्र के कामगार",
    empNeedQuestion: "आपको किस प्रकार की रोजगार सहायता चाहिए?",
    empNeedWage: "100 दिनों का गारंटीशुदा ग्रामीण रोजगार (मनरेगा)",
    empNeedSkill: "निःशुल्क कौशल विकास व उद्योग प्रशिक्षण (पीएमकेवीवाई)",
    empNeedPension: "वृद्धावस्था पेंशन व सामाजिक सुरक्षा (अटल पेंशन)",
    empNeedAccident: "कम खर्च में दुर्घटना बीमा सुरक्षा (सुरक्षा बीमा)",

    // Small Business Questions
    bizStatusQuestion: "आप किस प्रकार का व्यवसाय या कार्य करते हैं?",
    bizStatusVendor: "रेहड़ी-पटरी विक्रेता / फेरीवाले / ठेला चालक",
    bizStatusSmallBiz: "छोटा व्यवसाय / खुदरा दुकान संचालक",
    bizStatusSelf: "सूक्ष्म उद्यमी / स्वरोजगारी",
    bizStatusAspiring: "नया छोटा व्यवसाय शुरू करने की योजना",
    bizNeedQuestion: "आपको किस प्रकार की वित्तीय सहायता चाहिए?",
    bizNeedWorkingCap: "बिना गारंटी कार्यशील पूंजी ऋण (पीएम स्वनिधि ₹50,000 तक)",
    bizNeedMudra: "सूक्ष्म उद्यम हेतु व्यवसाय ऋण (मुद्रा लोन ₹10 लाख तक)",
    bizNeedBank: "जीरो-बैलेंस बैंक खाता, ओवरड्राफ्ट व बीमा (जन धन)",

    // Results Page
    resultsTitle: "आपके लिए प्रासंगिक हो सकती हैं ऐसी योजनाएँ",
    resultsCountPrefix: "आपकी दी गई जानकारी के आधार पर हमें",
    resultsCountSuffix: "योजनाएँ मिली हैं।",
    noticeLabel: "सूचना:",
    disclaimerText: "ये योजनाएँ प्रदान की गई जानकारी के आधार पर संभावित रूप से प्रासंगिक हैं। अंतिम पात्रता संबंधित सरकारी प्राधिकरण द्वारा निर्धारित की जाती है।",
    noResultsTitle: "दी गई जानकारी से मेल खाती योजनाएँ नहीं मिलीं",
    noResultsText: "आपकी दी गई जानकारी के आधार पर इस श्रेणी में सीधे मेल खाती योजनाएँ नहीं मिलीं। कृपया उत्तर बदलकर पुनः प्रयास करें।",
    changeAnswers: "उत्तर बदलें",
    startNewSearch: "नई खोज शुरू करें",

    // Web Scheme Discovery (independent Tavily pipeline, user-initiated)
    webSearchTitle: "वेब से और योजनाएँ",
    webSearchDesc: "ऊपर कोई योजना छूटी हो? हमारी सत्यापित सूची के अलावा आधिकारिक सरकारी वेबसाइटों पर अतिरिक्त योजनाएँ खोजें।",
    webSearchCta: "वेब पर और योजनाएँ खोजें",
    webSearchLoading: "आधिकारिक सरकारी वेबसाइटों पर खोज हो रही है... इसमें 30 सेकंड तक लग सकते हैं।",
    webSearchBadge: "वेब पर मिली",
    webSearchVerifyLink: "आधिकारिक पोर्टल पर सत्यापित करें",
    webSearchDisclaimer: "ये योजनाएँ वेब पर मिली हैं और प्रासंगिक हो सकती हैं। कृपया लाभ और पात्रता संबंधित आधिकारिक पोर्टल पर सत्यापित करें। अंतिम पात्रता संबंधित सरकारी प्राधिकरण द्वारा निर्धारित की जाती है।",
    webSearchRejectedNote: "अतिरिक्त असत्यापित परिणाम रोके गए",
    webSearchUnavailable: "वेब खोज अस्थायी रूप से अनुपलब्ध है या कोई अतिरिक्त सत्यापित योजना नहीं मिली। ऊपर दिए गए सत्यापित परिणाम अप्रभावित हैं।",
    webSearchNetworkError: "सर्वर से संपर्क नहीं हो सका। कृपया अपना कनेक्शन जाँचें और पुनः प्रयास करें।",
    webSearchGenericError: "वेब खोज विफल रही। कृपया बाद में पुनः प्रयास करें।",

    // Scheme Card
    liveGovSource: "लाइव • सरकारी स्रोत",
    liveGovSourceDesc: "आधिकारिक सरकारी पोर्टल से खोजा और सत्यापित किया गया",
    matchRelevance: "प्रासंगिकता स्कोर:",
    whyRelevant: "यह योजना आपके लिए क्यों प्रासंगिक हो सकती है",
    infoNeeded: "आवश्यक जानकारी व दस्तावेज",
    viewDetails: "योजना विवरण देखें",
    hideDetails: "विवरण छिपाएं",

    // Scheme Card Guidance (What do I do next?)
    nextStepsTitle: "अब क्या करें?",
    stepCheckEligibility: "इस योजना के लिए अपनी पात्रता की पुष्टि करें",
    stepPrepareDocuments: "ऊपर सूचीबद्ध जानकारी व दस्तावेज तैयार करें",
    stepApplyOnline: "आधिकारिक पोर्टल पर ऑनलाइन आवेदन भरें और जमा करें",
    stepTrackStatus: "पोर्टल के संदर्भ संख्या से आवेदन की स्थिति देखें",
    portalLabel: "आधिकारिक पोर्टल:",
    applyOnlineButton: "ऑनलाइन आवेदन करें ↗",
    applyOfflineLabel: "ऑफलाइन आवेदन",
    schemeDataInfoMissing: "मौजूदा डेटा में इस योजना के आवेदन विवरण उपलब्ध नहीं हैं।",
    whereToApplyTitle: "आवेदन कहाँ करें? (कार्यालय)",
    noLocationsFound: "चयनित क्षेत्र में इस योजना के लिए कोई विशिष्ट भौतिक कार्यालय पंजीकृत नहीं है। आप आधिकारिक पोर्टल पर ऑनलाइन आवेदन कर सकते हैं।",
    officeOfficialSource: "आधिकारिक पोर्टल",

    // Dynamic Reason Codes
    reason_ALL_INDIA_AVAILABLE: "पूरे भारत में उपलब्ध, जिसमें {state} भी शामिल है",
    reason_STATE_SPECIFIC_MATCH: "विशेष रूप से {state} के निवासियों के लिए उपलब्ध",
    reason_TARGET_GROUP_FARMER: "किसानों और ग्रामीण नागरिकों के लिए प्रासंगिक",
    reason_TARGET_GROUP_STUDENT: "विद्यार्थियों और युवाओं के लिए प्रासंगिक",
    reason_TARGET_GROUP_WOMEN: "महिलाओं के लिए लक्षित सहायता प्रदान करता है",
    reason_TARGET_GROUP_BUSINESS: "लघु व्यवसायों, फेरीवालों और उद्यमियों के लिए प्रासंगिक",
    reason_TARGET_GROUP_WORKER: "असंगठित और अकुशल श्रमिकों के लिए प्रासंगिक",
    reason_NEED_MATCH: "आपकी चुनी हुई आवश्यकता से मेल खाता है",
    reason_AGE_CRITERIA_MATCH: "आपकी आयु ({age} वर्ष) योजना के मानदंडों के अनुकूल है",
    reason_INCOME_CRITERIA_MATCH: "आपकी पारिवारिक आय योजना की सीमा के भीतर है",
    reason_LAND_OWNERSHIP_MATCH: "आपके कृषि भूमि स्वामित्व की स्थिति से मेल खाता है",
    reason_SOCIAL_CATEGORY_MATCH: "आपके सामाजिक वर्ग ({category}) के अनुकूल",
    reason_AREA_MATCH: "विशेष रूप से {area} क्षेत्रों के लिए निर्मित",
    reason_HOUSING_NEED_MATCH: "पक्के मकान से वंचित परिवारों के लिए उपयुक्त",

    // Scheme Detail Modal
    modalTitle: "योजना का संपूर्ण विवरण",
    departmentLabel: "विभाग / मंत्रालय:",
    aboutLabel: "योजना के बारे में",
    benefitsLabel: "मुख्य लाभ",
    documentsLabel: "आवश्यक जानकारी व दस्तावेज",
    applyButton: "आवेदन करें / अधिक जानें ↗",
    sourceButton: "आधिकारिक पोर्टल ↗",
    closeModal: "बंद करें",
    loadingDetails: "सत्यापित योजना जानकारी लोड हो रही है...",

    // Errors
    errorTitle: "अभी आपकी योजनाएँ नहीं मिल सकीं।",
    errorGeneric: "योजनाएं खोजते समय एक अप्रत्याशित समस्या आई। कृपया पुनः प्रयास करें।",
    errorNetwork: "सर्वर से संपर्क नहीं हो सका। कृपया इंटरनेट कनेक्शन या बैकएंड जांचें।",
    tryAgain: "पुनः प्रयास करें",
    startOver: "शुरू से करें",

    // Voice Assistant
    voicePageTitle: "वॉयस असिस्टेंट",
    voicePageSubtitle: "अंग्रेज़ी, हिंदी या मराठी में बोलें। असिस्टेंट आपको प्रासंगिक योजनाओं तक पहुंचने में मदद करेगा।",
    voiceRobotGreeting: "योजना ढूंढने में मदद चाहिए?",
    voiceWelcomeGreeting: "नमस्ते! मैं योजनासाथी हूँ। सरकारी योजनाओं की जानकारी के लिए मुझसे बात करें।",
    voicePanelTitle: "योजनासाथी वॉयस असिस्टेंट",
    voiceSelectLanguage: "कृपया अपनी भाषा चुनें",
    voiceLangChoiceHint: "असिस्टेंट आपके द्वारा चुनी गई भाषा में बात करेगा।",
    voiceLangLockedHint: "यह बातचीत इसी भाषा में रहेगी",
    voiceClosePanel: "वॉयस असिस्टेंट बंद करें",
    voiceMicIdleHint: "माइक्रोफ़ोन दबाकर बोलें",
    voiceMicHoldHint: "बोलने के लिए दबाए रखें",
    voiceMicReleaseHint: "भेजने के लिए छोड़ दें",
    voiceMicListening: "सुन रहे हैं…",
    voiceMicProcessing: "योजनाएँ खोजी जा रही हैं…",
    voiceMicSpeaking: "बोल रहे हैं…",
    voiceMicIdle: "बोलने के लिए टैप करें",
    voiceTapToSpeak: "बोलने के लिए टैप करें",
    voiceNewConversation: "नई बातचीत",
    voiceStopSpeaking: "आवाज़ रोकें",
    voiceYouSaid: "आपने कहा",
    voiceAssistantSaid: "असिस्टेंट",
    voiceAssistantLabel: "योजनासाथी असिस्टेंट",
    voiceUserLabel: "आप",
    voicePlayResponse: "उत्तर सुनें",
    voiceReplayResponse: "उत्तर दोबारा सुनें",
    voiceTranscriptLabel: "वॉयस असिस्टेंट वार्तालाप",
    voiceSchemesIntro: "आपके लिए प्रासंगिक हो सकने वाली कुछ योजनाएं ये हैं:",
    voiceStarterHeading: "आप पूछ सकते हैं:",
    voiceStarterFarmer: "महाराष्ट्र में किसान सहायता",
    voiceStarterScholarship: "छात्रों के लिए छात्रवृत्ति",
    voiceStarterHousing: "आवास सहायता",
    voicePlaceholder: "या यहाँ अपना प्रश्न लिखें…",
    voiceSendLabel: "संदेश भेजें",
    voiceErrorTitle: "क्षमा करें, कुछ गड़बड़ हो गई।",
    voiceErrorNetwork: "सर्वर से संपर्क नहीं हो सका। कृपया अपना कनेक्शन जांचकर पुनः प्रयास करें।",
    voiceErrorGeneric: "हम आपका अनुरोध पूरा नहीं कर सके। कृपया पुनः प्रयास करें।",
    voiceRetry: "पुनः प्रयास करें",
    voiceErrorMicPermission: "माइक्रोफ़ोन का उपयोग अनुमति नहीं दी गई। कृपया ब्राउज़र में माइक्रोफ़ोन अनुमति दें और पुनः प्रयास करें।",
    voiceErrorMicUnavailable: "माइक्रोफ़ोन अभी उपलब्ध नहीं है। कृपया अपने ऑडियो डिवाइस की जांच करें।",
    voiceErrorNoMicrophone: "इस डिवाइस पर कोई माइक्रोफ़ोन नहीं मिला।",
    voiceErrorUnsupported: "आपका ब्राउज़र वॉयस इनपुट समर्थित नहीं करता। कृपया Chrome, Edge, या Firefox का नवीनतम संस्करण उपयोग करें।",
    voiceErrorEmptyRecording: "कोई आवाज़ नहीं पहचानी गई। कृपया माइक्रोफ़ोन दबाकर दोबारा बोलें।",
    voiceErrorTts: "आवाज़ सुनाई नहीं दे सकी, लेकिन असिस्टेंट का उत्तर नीचे दिखाया गया है।",
    voicePlayBackFailed: "ब्राउज़र ने ऑडियो चलाने से रोका। सुनने के लिए “उत्तर सुनें” दबाएं।",
  },

  mr: {
    // Header
    appTitle: "योजनासाथी",
    appTagline: "सरकारी योजना शोधणे आता झाले सोपे",
    newSearch: "नवीन शोध",
    homeNav: "मुख्य पृष्ठ",
    languageSelect: "भाषा",
    mainNav: "मुख्य नेव्हिगेशन",
    navSchemeFinder: "योजना शोध",
    navVoiceAssistant: "व्हॉइस असिस्टंट",

    // Home Page & Category Grid
    heroBadge: "नागरिक योजना शोध मंच",
    heroTitle: "तुमच्यासाठी योग्य सरकारी योजना शोधा",
    heroSubtitle: "काही सोप्या प्रश्नांची उत्तरे द्या आणि तुमच्यासाठी उपयुक्त योजना जाणून घ्या.",
    categoryHeading: "तुम्हाला कोणत्या प्रकारची मदत हवी आहे?",
    categorySubtitle: "तुमच्या गरजेनुसार योग्य प्रवर्ग निवडा.",

    // Homepage Three Gateways
    homeHeroTitle: "सरकारी योजना सहज शोधा",
    homeHeroSubtitle: "तुम्हाला कशी मदत हवी ते निवडा. याला फक्त एक मिनिट लागेल.",
    gatewayWebsiteTitle: "मला संकेतस्थळ वापरता येते",
    gatewayWebsiteDesc: "योजना स्वतः ब्राउझ करा आणि शोधा",
    gatewayWebsiteCta: "ऑनलाइन योजना शोधा",
    gatewayVoiceTitle: "मला बोलून शोधायचे आहे",
    gatewayVoiceDesc: "योजनासाथी सहाय्यकाशी बोला",
    gatewayVoiceCta: "योजनासाथीशी बोला",
    gatewayPhoneTitle: "फोन / कॉल-ई",
    gatewayPhoneDesc: "वेबसाइट्स वापरत नाही? योजनासाथी AI-शक्तीवर चालणारा फोन सहाय्यक प्रदान करेल.",
    gatewayPhoneCta: "योजनासाथीला कॉल करा",
    gatewayPhoneNote: "लवकरच येत आहे",
    gatewayPhoneJudgeNote:
      "CALL-E इनबाउंड कॉलिंगसाठी एक पेड फोन नंबर आवश्यक आहे आणि त्यामधील टप्प्यात जोडला जाईल. CALL-E इंटिग्रेशन आणि सामायिक योजनासाथी स्कीम-मॅचिंग आर्किटेक्चर या MVP मध्ये आधीच लागू आहेत.",
    gatewaySecondaryHeading: "मदत मिळवण्याचे इतर मार्ग",
    gatewayVoicePrimaryLabel: "माझ्याशी बोला",
    gatewayVoicePrimaryHint: "बोलण्यासाठी कुठेही दाबा",
    gatewayVoicePrimaryAria: "तुमच्या भाषेत योजनासाथीशी बोला",
    quickTopicsHeading: "द्रुत विषय",
    quickTopicsSubtitle: "सुरुवात करण्यासाठी लोकप्रिय विषय",

    // Categories
    catFarmersTitle: "शेतकरी",
    catFarmersDesc: "शेती, पीक विमा आणि थेट आर्थिक सहाय्य योजना.",
    catWomenTitle: "महिला कल्याण",
    catWomenDesc: "आर्थिक सहाय्य, लाडकी बहीण आणि महिला सक्षमीकरण योजना.",
    catEducationTitle: "शिक्षण व विद्यार्थी",
    catEducationDesc: "शिष्यवृत्ती, विद्यार्थी सहाय्य आणि उच्च शिक्षण योजना.",
    catHealthcareTitle: "आरोग्य सेवा",
    catHealthcareDesc: "आरोग्य विमा आणि मोफत वैद्यकीय उपचार सहाय्य.",
    catHousingTitle: "घरकुल योजना",
    catHousingDesc: "पक्के घर बांधकाम आणि घरकुल सहाय्य योजना.",
    catEmploymentTitle: "रोजगार व कौशल्य",
    catEmploymentDesc: "रोजगार हमी, कौशल्य विकास आणि सामाजिक सुरक्षा.",
    catBusinessTitle: "लघु व्यवसाय",
    catBusinessDesc: "फेरीवाले, मुद्रा कर्ज आणि व्यवसाय सहाय्य.",

    // Questionnaire
    questionnaireTitlePrefix: "साठी योजना शोधत आहोत",
    questionnaireSubtitle: "चला तुमच्यासाठी उपयुक्त योजना शोधूया. यासाठी फक्त एक मिनिट लागेल.",
    stepIndicator: "टप्पा {current} / {total}",
    backButton: "← मागे जा",
    continueButton: "पुढे चला →",
    submitButton: "उपयुक्त योजना पहा 🎯",
    findingSchemesLoading: "तुमच्यासाठी योग्य योजना शोधत आहोत...",
    selectOptionPrompt: "कृपया पुढे जाण्यासाठी एक पर्याय निवडा.",

    // Questionnaire Common Questions
    ageQuestion: "तुमचे वय किती आहे?",
    agePlaceholder: "तुमचे वय टाका (उदा. 35)",
    ageError: "कृपया 10 ते 120 वर्षांच्या दरम्यान योग्य वय टाका.",
    stateQuestion: "तुम्ही कुठे राहता?",
    statePlaceholder: "-- आपले राज्य निवडा --",
    stateError: "कृपया यादीतून आपले राज्य निवडा.",
    districtQuestion: "तुम्ही कोणत्या जिल्ह्यात राहता?",
    districtPlaceholder: "-- जिल्हा निवडा (किंवा पुढे जा) --",
    districtPilotNote: "पायलट टप्पा: प्रत्यक्ष अर्ज कार्यालये सध्या नाशिक आणि पुणे जिल्ह्यांसाठी उपलब्ध आहेत. तुम्ही 'इतर' निवडू शकता किंवा पुढे जाऊ शकता.",
    talukaQuestion: "तुम्ही कोणत्या तालुक्यात राहता?",
    talukaPlaceholder: "-- तालुका निवडा (किंवा पुढे जा) --",
    otherDistrictOption: "इतर जिल्हा / वगळा",
    otherTalukaOption: "इतर तालुका / वगळा",
    loadingDistricts: "अधिकृत जिल्हे लोड होत आहेत...",
    loadingTalukas: "अधिकृत तालुके लोड होत आहेत...",
    errorLoadingDistricts: "सध्या जिल्हे लोड करता आले नाहीत.",
    errorLoadingTalukas: "सध्या तालुके लोड करता आले नाहीत.",
    retryLocationButton: "पुन्हा प्रयत्न करा",
    incomeQuestion: "तुमच्या कुटुंबाचे अंदाजे वार्षिक उत्पन्न किती आहे?",
    incomeBelow25: "₹2.5 लाखांपेक्षा कमी",
    income25to6: "₹2.5 लाख ते ₹6 लाख",
    incomeAbove6: "₹6 लाखांपेक्षा जास्त",
    incomeDontKnow: "माहित नाही / सांगायचे नाही",

    // Social Category Questions
    socialCategoryQuestion: "तुम्ही कोणत्या सामाजिक प्रवर्गातील आहात?",
    socialCatGeneral: "खुला प्रवर्ग (General)",
    socialCatSC: "अनुसूचित जाती (SC)",
    socialCatST: "अनुसूचित जमाती (ST)",
    socialCatOBC: "इतर मागासवर्गीय (OBC)",
    socialCatEBC: "आर्थिकदृष्ट्या मागास वर्ग (EBC)",
    socialCatDNT: "विमुक्त जाती किंवा भटक्या जमाती (DNT / VJNT / NT)",
    socialCatDontKnow: "माहित नाही / सांगायचे नाही",

    // Rural / Urban Area Questions
    areaQuestion: "तुम्ही ग्रामीण भागात राहता की शहरी भागात?",
    areaRural: "ग्रामीण भाग (गाव)",
    areaUrban: "शहरी भाग (शहर / नगर)",
    areaDontKnow: "माहित नाही / खात्री नाही",

    // Farmers Questions
    farmerLandQuestion: "तुमच्या किंवा तुमच्या कुटुंबाच्या नावावर शेतजमीन आहे का?",
    farmerLandYes: "होय, आमच्याकडे शेतजमीन आहे",
    farmerLandNo: "नाही, कुळ / बटाईदार किंवा भूमिहीन आहोत",
    farmerLandDontKnow: "माहित नाही / खात्री नाही",
    farmerNeedQuestion: "तुम्हाला कोणत्या प्रकारची मदत हवी आहे?",
    farmerNeedCropInsurance: "पीक विमा (पिकांच्या नुकसानीपासून संरक्षण)",
    farmerNeedDirectSupport: "थेट आर्थिक मदत (शेतकरी सन्मान निधी)",
    farmerNeedEquipment: "शेती अवजारे आणि खते-बियाणे मदत",
    farmerNeedLoan: "कृषी कर्ज किंवा किसान क्रेडिट कार्ड",

    // Women Questions
    womenStatusQuestion: "तुमची सध्याची परिस्थिती काय आहे?",
    womenStatusMarried: "विवाहित महिला",
    womenStatusUnmarried: "अविवाहित तरुणी / महिला",
    womenStatusPregnant: "गरोदर किंवा स्तनदा माता",
    womenStatusWidow: "विधवा, परित्यक्ता किंवा एकल महिला",
    womenStatusGeneral: "सांगायचे नाही",
    womenNeedQuestion: "तुम्ही कोणत्या प्रकारची मदत शोधत आहात?",
    womenNeedFinance: "महिलांसाठी मासिक आर्थिक मदत (लाडकी बहीण)",
    womenNeedGas: "मोफत गॅस सिलेंडर जोडणी (उज्ज्वला)",
    womenNeedMaternity: "मातृत्व आणि गरोदरपण आर्थिक मदत",
    womenNeedTraining: "कौशल्य प्रशिक्षण आणि स्वयंरोजगार मदत",

    // Education Questions
    eduStatusQuestion: "तुम्ही सध्या विद्यार्थी आहात किंवा शिक्षण घेत आहात का?",
    eduStatusYes: "होय, शाळा किंवा महाविद्यालयात शिकत आहोत",
    eduStatusNo: "नाही, शिक्षण किंवा कौशल्य प्रशिक्षणाची संधी शोधत आहोत",
    eduNeedQuestion: "तुम्हाला कोणत्या प्रकारची शैक्षणिक मदत हवी आहे?",
    eduNeedScholarship: "शालेय किंवा मॅट्रिकपूर्व/मॅट्रिकोत्तर शिष्यवृत्ती",
    eduNeedHigherEdu: "उच्च शिक्षण मदत आणि स्पर्धा परीक्षा कोचिंग",
    eduNeedSkill: "कौशल्य विकास आणि व्यावसायिक प्रमाणपत्र",

    // Healthcare Questions
    healthNeedQuestion: "तुम्हाला कोणत्या प्रकारची आरोग्य सेवा मदत हवी आहे?",
    healthNeedHospital: "रुग्णालयात उपचार आणि शस्त्रक्रिया सहाय्य",
    healthNeedInsurance: "मोफत आरोग्य विमा कार्ड (₹5 लाखांपर्यंत)",
    healthNeedSenior: "ज्येष्ठ नागरिक आरोग्य संरक्षण (वय 70+ वर्ष)",
    healthNeedCritical: "गंभीर आजार किंवा वैद्यकीय उपचार मदत",

    // Housing Questions
    housingPuccaQuestion: "तुमच्या किंवा तुमच्या कुटुंबाकडे पक्के घर आहे का?",
    housingPuccaNo: "नाही, कच्चे घर, तात्पुरते निवारे किंवा भाड्याने राहतो",
    housingPuccaYes: "होय, आमच्याकडे पक्के घर आहे",
    housingPuccaDontKnow: "माहित नाही / खात्री नाही",
    housingAreaQuestion: "तुम्ही घर कुठे बांधण्याची किंवा खरेदी करण्याची योजना आखत आहात?",
    housingAreaRural: "ग्रामीण भागात / गावात (पीएम आवास ग्रामीण)",
    housingAreaUrban: "शहरी भागात / नगरपालिका क्षेत्रात (पीएम आवास शहरी)",

    // Employment Questions
    empStatusQuestion: "तुमची सध्याची रोजगार स्थिती काय आहे?",
    empStatusUnemployed: "बेरोजगार / कामाच्या शोधात",
    empStatusWage: "दैनिक रोजंदारी मजूर / ग्रामीण कामगार",
    empStatusYouth: "कौशल्य प्रशिक्षण घेऊ इच्छिणारा तरुण",
    empStatusUnorganized: "असंघटित क्षेत्रातील कामगार",
    empNeedQuestion: "तुम्हाला कोणत्या प्रकारची रोजगार मदत हवी आहे?",
    empNeedWage: "100 दिवस हमीचे ग्रामीण रोजगार (मनरेगा)",
    empNeedSkill: "मोफत कौशल्य विकास व उद्योग प्रशिक्षण (पीएमकेव्हीवाय)",
    empNeedPension: "वृद्धापकाळ पेन्शन व सामाजिक सुरक्षा (अटल पेन्शन)",
    empNeedAccident: "कमी खर्चात अपघात विमा संरक्षण (सुरक्षा विमा)",

    // Small Business Questions
    bizStatusQuestion: "तुम्ही कोणत्या प्रकारचा व्यवसाय किंवा काम करता?",
    bizStatusVendor: "फेरीवाले / हातगाडी चालक / रस्त्यावरील विक्रेते",
    bizStatusSmallBiz: "लहान व्यवसाय / किरकोळ दुकानदार",
    bizStatusSelf: "सूक्ष्म उद्योजक / स्वयंरोजगार",
    bizStatusAspiring: "नवीन लहान व्यवसाय सुरू करण्याची योजना",
    bizNeedQuestion: "तुम्हाला कोणत्या प्रकारची आर्थिक मदत हवी आहे?",
    bizNeedWorkingCap: "विनातारण खेळते भांडवल कर्ज (पीएम स्वनिधी ₹50,000 पर्यंत)",
    bizNeedMudra: "सूक्ष्म उद्योगासाठी व्यवसाय कर्ज (मुद्रा कर्ज ₹10 लाखांपर्यंत)",
    bizNeedBank: "झिरो-बॅलन्स बँक खाते, ओव्हरड्राफ्ट व विमा (जन धन)",

    // Results Page
    resultsTitle: "तुमच्यासाठी उपयुक्त ठरू शकणाऱ्या योजना",
    resultsCountPrefix: "तुम्ही दिलेल्या माहितीच्या आधारे आम्हाला",
    resultsCountSuffix: "योजना सापडल्या आहेत.",
    noticeLabel: "सूचना:",
    disclaimerText: "दिलेल्या माहितीच्या आधारे या योजना संभाव्यतः उपयुक्त असू शकतात. अंतिम पात्रता संबंधित सरकारी प्राधिकरणाद्वारे निश्चित केली जाते.",
    noResultsTitle: "दिलेल्या माहितीशी जुळणाऱ्या योजना सापडल्या नाहीत",
    noResultsText: "तुम्ही दिलेल्या माहितीच्या आधारे या प्रवर्गात थेट जुळणाऱ्या योजना सापडल्या नाहीत. कृपया उत्तरे बदलून पुन्हा प्रयत्न करा.",
    changeAnswers: "उत्तरे बदला",
    startNewSearch: "नवीन शोध सुरू करा",

    // Web Scheme Discovery (independent Tavily pipeline, user-initiated)
    webSearchTitle: "वेबवरील आणखी योजना",
    webSearchDesc: "वर एखादी योजना राहिली आहे का? आमच्या सत्यापित यादीव्यतिरिक्त अधिकृत सरकारी वेबसाइटवर अतिरिक्त योजना शोधा.",
    webSearchCta: "वेबवर आणखी योजना शोधा",
    webSearchLoading: "अधिकृत सरकारी वेबसाइटवर शोध सुरू आहे... यास 30 सेकंदांपर्यंत वेळ लागू शकतो.",
    webSearchBadge: "वेबवर सापडली",
    webSearchVerifyLink: "अधिकृत पोर्टलवर पडताळणी करा",
    webSearchDisclaimer: "या योजना वेबवर सापडल्या असून उपयुक्त ठरू शकतात. कृपया लाभ व पात्रता संबंधित अधिकृत पोर्टलवर पडताळून पहा. अंतिम पात्रता संबंधित सरकारी प्राधिकरण ठरवते.",
    webSearchRejectedNote: "अतिरिक्त असत्यापित निकाल रोखले",
    webSearchUnavailable: "वेब शोध तात्पुरता अनुपलब्ध आहे किंवा अतिरिक्त सत्यापित योजना सापडल्या नाहीत. वरील सत्यापित निकालांवर परिणाम झालेला नाही.",
    webSearchNetworkError: "सर्व्हरशी संपर्क होऊ शकला नाही. कृपया कनेक्शन तपासून पुन्हा प्रयत्न करा.",
    webSearchGenericError: "वेब शोध अयशस्वी झाला. कृपया नंतर पुन्हा प्रयत्न करा.",

    // Scheme Card
    liveGovSource: "थेट • शासकीय स्रोत",
    liveGovSourceDesc: "अधिकृत शासकीय पोर्टलवरून शोधलेले व पडताळलेले",
    matchRelevance: "सुसंगतता गुण:",
    whyRelevant: "ही योजना तुमच्यासाठी का उपयुक्त ठरू शकते",
    infoNeeded: "आवश्यक कागदपत्रे व माहिती",
    viewDetails: "योजनेचा तपशील पहा",
    hideDetails: "तपशील लपवा",

    // Scheme Card Guidance (What do I do next?)
    nextStepsTitle: "आता काय करावे?",
    stepCheckEligibility: "या योजनेच्या अटींसाठी तुमची पात्रता निश्चित करा",
    stepPrepareDocuments: "वर सूचीबद्ध माहिती व कागदपत्रे तयार करा",
    stepApplyOnline: "अधिकृत पोर्टलवर ऑनलाइन अर्ज भरा व सादर करा",
    stepTrackStatus: "पोर्टलच्या संदर्भ क्रमांकाने अर्जाची स्थिती तपासा",
    portalLabel: "अधिकृत पोर्टल:",
    applyOnlineButton: "ऑनलाइन अर्ज करा ↗",
    applyOfflineLabel: "ऑफलाइन अर्ज",
    schemeDataInfoMissing: "सध्याच्या डेटामध्ये या योजनेच्या अर्जाची माहिती उपलब्ध नाही.",
    whereToApplyTitle: "अर्ज कोठे करावा? (प्रत्यक्ष कार्यालय)",
    noLocationsFound: "निवडलेल्या क्षेत्रात या योजनेसाठी कोणतेही विशिष्ट प्रत्यक्ष कार्यालय नोंदणीकृत नाही. तुम्ही अधिकृत पोर्टलद्वारे ऑनलाइन अर्ज करू शकता.",
    officeOfficialSource: "अधिकृत पोर्टल",

    // Dynamic Reason Codes
    reason_ALL_INDIA_AVAILABLE: "संपूर्ण भारतात लागू, ज्यामध्ये {state} चा समावेश आहे",
    reason_STATE_SPECIFIC_MATCH: "विशेषतः {state} च्या रहिवाशांसाठी उपलब्ध",
    reason_TARGET_GROUP_FARMER: "शेतकरी आणि ग्रामीण नागरिकांसाठी उपयुक्त",
    reason_TARGET_GROUP_STUDENT: "विद्यार्थी आणि तरुणांसाठी उपयुक्त",
    reason_TARGET_GROUP_WOMEN: "महिलांसाठी विशेष साहाय्य पुरवते",
    reason_TARGET_GROUP_BUSINESS: "लहान व्यवसाय, फेरीवाले आणि नवउद्योजकांसाठी उपयुक्त",
    reason_TARGET_GROUP_WORKER: "असंघटित आणि अकुशल कामगारांसाठी उपयुक्त",
    reason_NEED_MATCH: "तुमच्या निवडलेल्या गरजेनुसार सुसंगत",
    reason_AGE_CRITERIA_MATCH: "तुमचे वय ({age} वर्षे) योजनेच्या अटींशी जुळणारे आहे",
    reason_INCOME_CRITERIA_MATCH: "तुमचे उत्पन्न योजनेच्या निकषांतर्गत आहे",
    reason_LAND_OWNERSHIP_MATCH: "तुमच्या शेतजमीन मालकी हक्काशी जुळणारे",
    reason_SOCIAL_CATEGORY_MATCH: "तुमच्या सामाजिक प्रवर्गाशी ({category}) सुसंगत",
    reason_AREA_MATCH: "विशेषतः {area} भागासाठी तयार केलेली",
    reason_HOUSING_NEED_MATCH: "पक्के घर नसलेल्या कुटुंबांसाठी उपयुक्त",

    // Scheme Detail Modal
    modalTitle: "योजनेचा संपूर्ण तपशील",
    departmentLabel: "विभाग / मंत्रालय:",
    aboutLabel: "योजनेबद्दल",
    benefitsLabel: "मुख्य फायदे",
    documentsLabel: "आवश्यक कागदपत्रे व माहिती",
    applyButton: "अर्ज करा / अधिक माहिती ↗",
    sourceButton: "अधिकृत संकेतस्थळ ↗",
    closeModal: "बंद करा",
    loadingDetails: "सत्यापित योजनेची माहिती लोड होत आहे...",

    // Errors
    errorTitle: "सध्या तुमच्यासाठी योजना शोधता आल्या नाहीत.",
    errorGeneric: "योजना शोधताना अनपेक्षित अडचण आली. कृपया पुन्हा प्रयत्न करा.",
    errorNetwork: "सर्व्हरशी संपर्क होऊ शकला नाही. कृपया इंटरनेट कनेक्शन किंवा बॅकएंड तपासा.",
    tryAgain: "पुन्हा प्रयत्न करा",
    startOver: "सुरुवातीपासून करा",

    // Voice Assistant
    voicePageTitle: "व्हॉइस असिस्टंट",
    voicePageSubtitle: "इंग्रजी, हिंदी किंवा मराठीत बोला. असिस्टंट तुम्हाला उपयुक्त योजना शोधण्यात मदत करेल.",
    voiceRobotGreeting: "योजना शोधण्यात मदत हवी?",
    voiceWelcomeGreeting: "नमस्कार! मी योजनासाथी आहे. सरकारी योजनांची माहिती मिळवण्यासाठी माझ्याशी बोला.",
    voicePanelTitle: "योजनासाथी व्हॉइस असिस्टंट",
    voiceSelectLanguage: "कृपया तुमची भाषा निवडा",
    voiceLangChoiceHint: "असिस्टंट तुम्ही निवडलेल्या भाषेत बोलेल.",
    voiceLangLockedHint: "ही बातचीत याच भाषेत राहील",
    voiceClosePanel: "व्हॉइस असिस्टंट बंद करा",
    voiceMicIdleHint: "बोलण्यासाठी मायक्रोफोन दाबा",
    voiceMicHoldHint: "बोलण्यासाठी दाबून ठेवा",
    voiceMicReleaseHint: "पाठवण्यासाठी सोडा",
    voiceMicListening: "ऐकत आहोत…",
    voiceMicProcessing: "योजना शोधत आहोत…",
    voiceMicSpeaking: "बोलत आहोत…",
    voiceMicIdle: "बोलण्यासाठी टॅप करा",
    voiceTapToSpeak: "बोलण्यासाठी टॅप करा",
    voiceNewConversation: "नवीन संवाद",
    voiceStopSpeaking: "आवाज थांबवा",
    voiceYouSaid: "तुम्ही म्हणालात",
    voiceAssistantSaid: "सहाय्यक",
    voiceAssistantLabel: "योजनासाथी सहाय्यक",
    voiceUserLabel: "तू/तुम्ही",
    voicePlayResponse: "उत्तर ऐका",
    voiceReplayResponse: "उत्तर पुन्हा ऐका",
    voiceTranscriptLabel: "व्हॉइस सहाय्यक संवाद",
    voiceSchemesIntro: "तुमच्यासाठी उपयुक्त ठरू शकणाऱ्या काही योजना या आहेत:",
    voiceStarterHeading: "तुम्ही विचारू शकता:",
    voiceStarterFarmer: "महाराष्ट्रातील शेतकरी सहाय्य",
    voiceStarterScholarship: "विद्यार्थ्यांसाठी शिष्यवृत्ती",
    voiceStarterHousing: "घरकुल सहाय्य",
    voicePlaceholder: "किंवा तुमचा प्रश्न इथे लिहा…",
    voiceSendLabel: "संदेश पाठवा",
    voiceErrorTitle: "क्षमा करा, काहीतरी चूक झाली.",
    voiceErrorNetwork: "सर्व्हरशी संपर्क करता आला नाही. कृपया आपले कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
    voiceErrorGeneric: "आम्ही तुमचा विनंती पूर्ण करू शकलो नाही. कृपया पुन्हा प्रयत्न करा.",
    voiceRetry: "पुन्हा प्रयत्न करा",
    voiceErrorMicPermission: "मायक्रोफोन वापरण्याची परवानगी मिळाली नाही. कृपया ब्राउझरमध्ये मायक्रोफोन परवानगी द्या आणि पुन्हा प्रयत्न करा.",
    voiceErrorMicUnavailable: "मायक्रोफोन सध्या उपलब्ध नाही. कृपया तुमची ऑडिओ उपकरणे तपासून पुन्हा प्रयत्न करा.",
    voiceErrorNoMicrophone: "या डिव्हाइसवर मायक्रोफोन आढळला नाही.",
    voiceErrorUnsupported: "तुमचा ब्राउझर व्हॉइस इनपुट समर्थित करत नाही. कृपया Chrome, Edge, किंवा Firefox ची नवीनतम आवृत्ती वापरा.",
    voiceErrorEmptyRecording: "कोणताही आवाज आढळला नाही. कृपया मायक्रोफोन दाबून पुन्हा बोला.",
    voiceErrorTts: "आवाज ऐकू येऊ शकला नाही, परंतु सहाय्यकाचे उत्तर खाली दाखवले आहे.",
    voicePlayBackFailed: "ब्राउझरने ऑडिओ चालवण्यास रोखले. ऐकण्यासाठी “उत्तर ऐका” दाबा.",
  },
};

/**
 * Helper to get localized string with fallback to English.
 * @param {string} lang - Current language code ('en', 'hi', 'mr')
 * @param {string} key - String identifier key
 * @param {object} params - Optional replacements (e.g. { current: 1, total: 4 })
 * @returns {string} - Localized string
 */
export function getLocaleString(lang, key, params = {}) {
  const langDict = STRINGS[lang] || STRINGS.en;
  let text = langDict[key] || STRINGS.en[key] || key;
  if (params && typeof text === 'string') {
    Object.keys(params).forEach((paramKey) => {
      text = text.replaceAll(`{${paramKey}}`, params[paramKey]);
    });
  }
  return text;
}

export const CURRENT_LANG = "en";
export const t = (key, params) => getLocaleString(CURRENT_LANG, key, params);
